server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # TODO : ?? Service URL? ????
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
        routes:
          - id: logout
            uri: lb://user-service
            predicates:
              - Path=/api/user/logout
            filters:
              - StripPrefix=1
              - name: AuthorizationHeaderFilter # 특정 라우트에만 필터 적용
              - name: LogoutAuthorizationHeaderFilter
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user/info/**
            filters:
              - StripPrefix=1 # "/api/u
              - name: AuthorizationHeaderFilter
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user/**, /api/mail/**
            filters:
              - StripPrefix=1 # "/api/user-service" 부분을 제거하여 "/sign-up"으로 전달


management:
  endpoints:
    web:
      exposure:
        include: "*"