server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # TODO : ?? Service URL? ????
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      mvc:
        routes:
          # TODO : Micro Service ??
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/user

management:
  endpoints:
    web:
      exposure:
        include: "*"